image: golang:latest

stages:
  - test
  - build

test:
  stage: test
  script:
    - go generate ./...
    - go test -v -race ./...

vet:
  stage: test
  script:
    - go vet ./...

golangci-lint:
  stage: test
  image:
    name: golangci/golangci-lint:latest
    entrypoint: [""]
  script:
    - go get
    - go generate ./...
    - golangci-lint run ./...

build:
  stage: build
  script:
    - go generate ./...
    - go build ./...

build-docker:
  stage: build
  tags:
    - docker
  image: docker:latest
  services:
    - docker:dind
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN r.gitlab.schoentoon.com
    - docker build -t r.gitlab.schoentoon.com/schoentoon/event-bot .
    - docker push r.gitlab.schoentoon.com/schoentoon/event-bot