telegram:
  token: "REPLACE THIS WITH YOUR OWN TOKEN"
  debug: true
postgres:
  addr: "user=events host=db dbname=events password=3v3n5 sslmode=disable"
workers: 8
templates: ./tmpl
eventRefreshInterval: 500ms