version: '2'
services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 3v3n5
      POSTGRES_USER: events
      POSTGRES_DB: events

  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml
      - ./tmpl/:/app/tmpl/
    command: [ "-config", "/app/config.yml" ]
    links:
      - db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
#      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - bot
      - postgres_exporter

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://events:3v3n5@db:5432/events?sslmode=disable"
      PG_EXPORTER_DISABLE_SETTINGS_METRICS: "true"
    links:
      - db
